package biblioteca.vista;

public enum Opcion {
    SALIR,
    INSERTAR_USUARIO,
    BORRAR_USUARIO,
    MOSTRAR_USUARIO,
    INSERTAR_LIBRO,
    BORRAR_LIBRO,
    MOSTRAR_LIBRO,
    NUEVO_PRESTAMO,
    DEVOLVER_PRESTAMOS,
    MOSTRAR_PRESTAMOS,
    MOSTRAR_PRESTAMOS_USUARIOS

}
